"""Add customer_interactions and customer_segments tables

Revision ID: b4f8c2d1a9e0
Revises: 022f8e890f40
Create Date: 2025-08-23 06:01:30.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4f8c2d1a9e0'
down_revision = '022f8e890f40'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create customer_interactions table
    op.create_table('customer_interactions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('organization_id', sa.Integer(), nullable=False),
        sa.Column('customer_id', sa.Integer(), nullable=False),
        sa.Column('interaction_type', sa.String(), nullable=False),
        sa.Column('subject', sa.String(), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('status', sa.String(), nullable=False),
        sa.Column('interaction_date', sa.DateTime(timezone=True), nullable=False),
        sa.Column('created_by', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
        sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
        sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_customer_interaction_date', 'customer_interactions', ['interaction_date'], unique=False)
    op.create_index('idx_customer_interaction_org_customer', 'customer_interactions', ['organization_id', 'customer_id'], unique=False)
    op.create_index('idx_customer_interaction_type_status', 'customer_interactions', ['interaction_type', 'status'], unique=False)
    op.create_index(op.f('ix_customer_interactions_id'), 'customer_interactions', ['id'], unique=False)
    op.create_index(op.f('ix_customer_interactions_organization_id'), 'customer_interactions', ['organization_id'], unique=False)
    
    # Create customer_segments table
    op.create_table('customer_segments',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('organization_id', sa.Integer(), nullable=False),
        sa.Column('customer_id', sa.Integer(), nullable=False),
        sa.Column('segment_name', sa.String(), nullable=False),
        sa.Column('segment_value', sa.Float(), nullable=True),
        sa.Column('segment_description', sa.Text(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('assigned_date', sa.DateTime(timezone=True), nullable=False),
        sa.Column('assigned_by', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
        sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
        sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('organization_id', 'customer_id', 'segment_name', name='uq_customer_segment_org_customer_name')
    )
    op.create_index('idx_customer_segment_assigned_date', 'customer_segments', ['assigned_date'], unique=False)
    op.create_index('idx_customer_segment_name_active', 'customer_segments', ['segment_name', 'is_active'], unique=False)
    op.create_index('idx_customer_segment_org_customer', 'customer_segments', ['organization_id', 'customer_id'], unique=False)
    op.create_index(op.f('ix_customer_segments_id'), 'customer_segments', ['id'], unique=False)
    op.create_index(op.f('ix_customer_segments_organization_id'), 'customer_segments', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop customer_segments table
    op.drop_index(op.f('ix_customer_segments_organization_id'), table_name='customer_segments')
    op.drop_index(op.f('ix_customer_segments_id'), table_name='customer_segments')
    op.drop_index('idx_customer_segment_org_customer', table_name='customer_segments')
    op.drop_index('idx_customer_segment_name_active', table_name='customer_segments')
    op.drop_index('idx_customer_segment_assigned_date', table_name='customer_segments')
    op.drop_table('customer_segments')
    
    # Drop customer_interactions table
    op.drop_index(op.f('ix_customer_interactions_organization_id'), table_name='customer_interactions')
    op.drop_index(op.f('ix_customer_interactions_id'), table_name='customer_interactions')
    op.drop_index('idx_customer_interaction_type_status', table_name='customer_interactions')
    op.drop_index('idx_customer_interaction_org_customer', table_name='customer_interactions')
    op.drop_index('idx_customer_interaction_date', table_name='customer_interactions')
    op.drop_table('customer_interactions')
    # ### end Alembic commands ###