"""Add customer interactions and segments tables

Revision ID: ccb764a60b10
Revises: 022f8e890f40
Create Date: 2025-01-27 06:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccb764a60b10'
down_revision = '022f8e890f40'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create customer_interactions table
    op.create_table('customer_interactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_customer_interaction_org_customer', 'customer_interactions', ['organization_id', 'customer_id'], unique=False)
    op.create_index('idx_customer_interaction_org_date', 'customer_interactions', ['organization_id', 'date'], unique=False)
    op.create_index('idx_customer_interaction_org_type', 'customer_interactions', ['organization_id', 'type'], unique=False)
    op.create_index(op.f('ix_customer_interactions_id'), 'customer_interactions', ['id'], unique=False)
    op.create_index(op.f('ix_customer_interactions_customer_id'), 'customer_interactions', ['customer_id'], unique=False)
    op.create_index(op.f('ix_customer_interactions_organization_id'), 'customer_interactions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_customer_interactions_type'), 'customer_interactions', ['type'], unique=False)
    
    # Create customer_segments table
    op.create_table('customer_segments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'name', name='uq_customer_segment_org_name')
    )
    op.create_index('idx_customer_segment_org_name', 'customer_segments', ['organization_id', 'name'], unique=False)
    op.create_index(op.f('ix_customer_segments_id'), 'customer_segments', ['id'], unique=False)
    op.create_index(op.f('ix_customer_segments_name'), 'customer_segments', ['name'], unique=False)
    op.create_index(op.f('ix_customer_segments_organization_id'), 'customer_segments', ['organization_id'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop customer_segments table
    op.drop_index(op.f('ix_customer_segments_organization_id'), table_name='customer_segments')
    op.drop_index(op.f('ix_customer_segments_name'), table_name='customer_segments')
    op.drop_index(op.f('ix_customer_segments_id'), table_name='customer_segments')
    op.drop_index('idx_customer_segment_org_name', table_name='customer_segments')
    op.drop_table('customer_segments')
    
    # Drop customer_interactions table
    op.drop_index(op.f('ix_customer_interactions_type'), table_name='customer_interactions')
    op.drop_index(op.f('ix_customer_interactions_organization_id'), table_name='customer_interactions')
    op.drop_index(op.f('ix_customer_interactions_customer_id'), table_name='customer_interactions')
    op.drop_index(op.f('ix_customer_interactions_id'), table_name='customer_interactions')
    op.drop_index('idx_customer_interaction_org_type', table_name='customer_interactions')
    op.drop_index('idx_customer_interaction_org_date', table_name='customer_interactions')
    op.drop_index('idx_customer_interaction_org_customer', table_name='customer_interactions')
    op.drop_table('customer_interactions')
    
    # ### end Alembic commands ###